# Generated by Django 5.0.6 on 2024-07-08 05:20

import goods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='cag_img',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_img',
            field=models.ImageField(upload_to=goods.models.CustomPathAndRename('static/goods/')),
        ),
    ]
